# Generated by Django 4.1.13 on 2024-08-03 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Actions',
        ),
        migrations.DeleteModel(
            name='Articles',
        ),
        migrations.DeleteModel(
            name='Categories',
        ),
        migrations.DeleteModel(
            name='Impression',
        ),
        migrations.DeleteModel(
            name='Mediauser',
        ),
        migrations.DeleteModel(
            name='Social',
        ),
    ]
